# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '2.6.3'

gem 'puma', '~> 4.3'
gem 'rack-cors', '~> 1.0.5'
gem 'rails', '~> 5.1.7'
gem 'sqlite3', '~> 1.4.1'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 5.0'
  gem 'rspec-rails', '~> 3.8'
  gem 'simplecov', '~> 0.17.1'
  gem 'faker', '~> 2.2.1'
  gem 'capybara', '~> 3.29.0'
  gem 'phantomjs', '~> 2.1.1.0'
  gem 'poltergeist', '~> 1.18.1'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring', '~> 2.1.0'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
